version: '3.8'

services:
  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: payload_db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d payload_db"]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    build: .
    ports:
      - "3000:3000"
    environment:
      - DATABASE_URL=postgresql://user:password@db:5432/payload_db
      - PAYLOAD_SECRET=your-secret-key-change-this-in-production
      - NEXT_PUBLIC_SERVER_URL=http://localhost:3000
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ./media:/app/media

volumes:
  postgres_data: 